version: "3.9"

services:

  postgres-bikestore-example:
    image: postgres:15.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5438:5432'
    volumes:
      - ./example/postgres-data:/var/lib/postgresql/data
      - ./example/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./example/sql/fill_tables.sql:/docker-entrypoint-initdb.d/fill_tables.sql
