version: "3.9"

services:

  connector-runtime:
    image: camunda/connectors:0.10.0
    networks:
      - connector-network
    env_file: ./connector-secrets.txt
    environment:
      LLM_SERVICE_URL: http://llm-service:9999
    volumes:
      - ./core/target/camunda-8-connector-gpt-core-0.1.1-SNAPSHOT-with-dependencies.jar:/opt/app/connector.jar

  llm-service:
    build:
      context: python
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    networks:
      - connector-network
    env_file: ./connector-secrets.txt

networks:
  connector-network:
