name: CI for special branches

on:
  push:
    branches:
      - '!master'
      - '!develop'
      - '!release/*'
      - '*/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        jdk: ['11.0.5']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.jdk }}
          cache: maven

      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean verify -U -B -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
